const getters = {
  sidebar: state => state.app.sidebar,
  token: state => state.user.token,
  avatar: state => state.user.avatar,
  name: state => state.user.name,
  introduction: state => state.user.introduction,
  status: state => state.user.status,
  roles: state => state.user.roles,
  setting: state => state.user.setting,
  permission_routers: state => state.permission.routers,
  addRouters: state => state.permission.addRouters,
  errorLogs: state => state.errorLog.logs,
  // userInfo: state => state.user.userInfo,
  experience:state=>state.user.Experience,
  type_select: state => state.app.type_select,
  guild_type: state => state.app.guild_type,
  platform: state => state.app.platform,
  category: state => state.app.category,
  special_manager: state => state.app.special_manager,
  guildInfo: state => state.app.guildInfo,
  total_type: state => state.app.total_type,
  anchorInfo: state => state.app.anchorInfo,
  audienceInfo: state => state.app.audienceInfo,
  comparison: state => state.app.comparison
};
export default getters
